config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get "about", to: "pages#about"
  get "faq", to: "pages#faq"
  get "imprint", to: "pages#imprint"
  get "agb", to: "pages#agb"
  get "admin", to: "pages#admin"

  resources :subscribers, only: [:new, :create, :index]

  resources :products do
    collection do
      get :shirt, :voucher
    end
  end

  resources :orders, only: [:show, :new, :create] do
    resources :payments, only: [:new]
  end

  resources :orders, only: [:show, :new, :create] do
    resources :deliveries, only: [:new, :create, :show]
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/shared/_delivery_form.html.erb
<div class="delivery-form">

    <%= simple_form_for [@order, @delivery] do |f| %>
    <%= f.error_notification %>

      <div class="form-inputs">
      <%= f.input :first_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "first_name" } %>
      <%= f.input :last_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "last_name" } %>
      <%= f.input :email,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :street,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :house_number,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :city,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :post_code,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :country, placeholder: "Germany",
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      </div>

      <div class="form-actions button-centered">
        <%= f.button :submit, "Submit your info", class: "btn btn-flat wj-150" %>
      </div>
    <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/jungbusch_berlin/?hl=en"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/jungbuschberlin/"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright" id="imprint-font">
    <%= link_to "Impressum", imprint_path %>
    <%= link_to "AGB", agb_path %>
    Made with <i class="fas fa-heart"></i> in Berlin
  </div>
</div>

app/views/shared/_footerabout.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/jungbusch_berlin/?hl=en"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/jungbuschberlin/"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright" id="imprint-font">
    <%= link_to "Impressum", imprint_path %>
    Made with <i class="fas fa-heart"></i> in Berlin
  </div>
</div>

app/views/shared/_footerhome.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/jungbusch_berlin/?hl=en"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/jungbuschberlin/"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright" id="imprint-font">
    <%= link_to "Impressum", imprint_path %>
    Made with <i class="fas fa-heart"></i> in Berlin
  </div>
</div>

app/views/shared/_footerpages.html.erb
<div class="footer-pages">
  <div class="footer-links">
    <a href="https://www.instagram.com/jungbusch_berlin/?hl=en"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/jungbuschberlin/"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> in Berlin
  </div>
</div>

app/views/shared/_google_analytics.html.erb
<% if Rails.env.production? %>
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= Rails.application.credentials.dig(:google_analytics) %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<%= Rails.application.credentials.dig(:google_analytics) %>');
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-jb fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-white.png" %>
    <% end %>

  <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="nav-content">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "JB SAYS HI", about_path, class: "nav-link", id:"navbar-font" %>
        </li>
        <li class="nav-item">
          <li class="nav-item dropdown">
          <%= link_to "MARKET", '#', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Vouchers", voucher_products_path, class: "dropdown-item" %>
                <%= link_to "Shirts", shirt_products_path, class: "dropdown-item" %>
                <%= link_to "All Products", products_path, class: "dropdown-item" %>
              </div>
            </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag(current_user.photo.key,
                crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% else %>
              <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <% end %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "LOGIN | REGISTER", new_user_session_path, class: "nav-link", id:"navbar-font" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<!--           <span class="badge badge-pill badge-light" id="soon-font">Soon!</span> -->

app/views/shared/_order_form.html.erb
<div class="signup-container">

    <%= simple_form_for @order do |f| %>
    <%= f.error_notification %>

      <div class="form-inputs">
      <%= f.input :first_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "first_name" } %>
      <%= f.input :last_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "last_name" } %>
      <%= f.input :email,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :street,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :house_number,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :city,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :post_code,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :country, placeholder: "Germany",
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      </div>

      <div class="form-actions button-centered">
        <%= f.button :submit, "Next", class: "btn btn-flat wj-100" %>
      </div>
    <% end %>
</div>