config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get "about", to: "pages#about"
  get "faq", to: "pages#faq"
  get "imprint", to: "pages#imprint"
  get "agb", to: "pages#agb"
  get "admin", to: "pages#admin"

  resources :subscribers, only: [:new, :create, :index]

  resources :products do
    collection do
      get :shirt, :voucher
    end
  end

  resources :orders, only: [:show, :new, :create] do
    resources :payments, only: [:new]
  end

  resources :orders, only: [:show, :new, :create] do
    resources :deliveries, only: [:new, :create, :show]
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :sku, :name, :description, :price, :delivery, :note, presence: true
  monetize :price_cents
  has_many :pictures, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :voucher, :shirt]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    @products = policy_scope(Product).order(created_at: :desc)
  end

  def show
    @order = Order.new
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    authorize @product
    @product.save

    if @product.save
      create_pictures
      redirect_to product_path(@product), notice: "Product was succesfully published."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), notice: "Product was succesfully updated."
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: "Product was succesfully deleted."
  end

  def voucher
    @products = Product.where(sku: 1)
    authorize @products
  end

  def shirt
    @products = Product.where(sku: 2)
    authorize @products
  end

  private

  def product_params
    params.require(:product).permit(:sku, :name, :description, :price_cents, :color, :fabric, :delivery, :size, :note, :quantity, :pictures)
  end

  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end

  def create_pictures
    photos = params.dig(:product, :pictures) || []
    photos.each do |photo|
      @product.pictures.create(photo: photo)
  end
end

end

app/views/products/_form.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-jb">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
</div>

</br>

<div class="class new-container">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-6">
        <h2>Publish/Update a Product</h2>
        <h3>
          <%= simple_form_for @product do |f| %>
            <%= f.input :sku %>
            <%= f.input :pictures, as: :file, input_html: { multiple: true} %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :price_cents, label: 'Price' %>
            <%= f.input :size %>
            <%= f.input :color %>
            <%= f.input :fabric %>
            <%= f.input :delivery %>
            <%= f.input :note %>
            <%= f.button :submit, class: 'btn btn-publish' %>
        <% end %>
        </h3>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="container-black">
  <div class="navbar navbar-expand-sm navbar-light navbar-jb">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-black.jpg" %>
      <% end %>
  </div>

 <%#= link_to "Add new", new_product_path, class: '#' %>

<div class="product-container">
  <div class="index-container">
    <h1>ALL PRODUCTS</h1>
      <div class="product-cards">
        <% @products.each do |product| %>
          <%= link_to product_path(product) do %>
            <div class="card-trip">
              <% if product.pictures[0].photo.nil? %>
                <%= cl_image_tag 'https://res.cloudinary.com/djkmpmlvq/image/upload/v1587120323/vvz87tdsubzir1jztrvd34u4311q.jpg' %>
              <% else %>
                <%= cl_image_tag product.pictures[0].photo %>
              <% end %>
                <div class="card-trip-infos">
                  <div>
                    <h2> <%= product.name %></h2>
                    <p> <%= product.color %></p>
                    <h3> <%= product.size %></h3>
                  </div>
                  <h1 class="card-trip-pricing"><h1><%= humanized_money_with_symbol(product.price) %></h1>
                  <%#= cl_image_tag product.user.photo.key, class: "card-trip-user avatar-bordered" %>
                </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

<%= render 'shared/footer' %>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/shirt.html.erb
<div class="container-black">
  <div class="navbar navbar-expand-sm navbar-light navbar-jb">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-black.jpg" %>
      <% end %>
  </div>

<div class="product-container">

<div class="index-container">
  <h1>SHIRTS</h1>
    <div class="product-cards">
      <% @products.each do |product| %>
        <%= link_to product_path(product) do %>
          <div class="card-trip">
            <%= cl_image_tag product.pictures[0].photo %>
              <div class="card-trip-infos">
                <div>
                  <h2> <%= product.name %></h2>
                  <p> <%= product.color %></p>
                  <h3> <%= product.size %></h3>
                </div>
                <h1 class="card-trip-pricing"><h1><%= humanized_money_with_symbol(product.price) %></h1>
                <%#= cl_image_tag product.user.photo.key, class: "card-trip-user avatar-bordered" %>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

</br>
</br>
</br>
</br>


</div>

app/views/products/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-jb">
  <%= link_to products_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
</div>

<%#= link_to 'Delete', product_path(@product), method: :delete, data: { confirm: 'Are you sure?' } %>

<div class="newshow-container">

    <div class="bg-white">
      <div class="container p-3">
        <div class="row">
          <div class="col-md-8" id="product-size">
            <% @product.pictures.each do |picture| %>
            <%= cl_image_tag(picture.photo) %>
            <% end %>
          </div>
          <div class="col-md-4">
            <h1><%= @product.name %></h1>
            </br>
            <h4><%= @product.color %></h4>
            <h4><%= @product.fabric %></h4>
            <h4><%= @product.size %></h4>
          </br>
          </br>
          <% if @product.size.empty? %>
              <p></p>
          <% else %>
            <%= image_tag "ep-logo.png", width: '70' %>
            <%= image_tag "fair-logo.png", width: '120'%>
            <%= image_tag "peta-logo.jpg", width: '120' %>
          <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container py-3" id="checkout-font">
      <div class="row">
        <div class="col-md-8">

          <div class="card p-3 mb-3">
            <h1>Product Details</h1>
            <p><%= @product.description %></p>
          </div>
          <% if @product.size.empty? %>
              <p></p>
          <% else %>
          <div class="card p-3 mb-3">
            <h1>Product Size</h1>
            <%= image_tag "shirt-size.png", width: '700' %>
          <% end %>
          </div>
        </div>

        <div class="col-md-4">

          <div class="bg-white border p-3 sticky-top">
            <div class="d-flex justify-content-between mt-3">
              <p>Total Price</p>
              <h2 id="euro">€</h2>
              <div class="product-price">
                  <h2 id="product-price"><%= @product.price %></h2>
              </div>
                <%= form_tag orders_path do %> <%= hidden_field_tag 'product_id', @product.id %>
          </div>

          <% if @product.size.empty? %>
              <p></p>
          <% else %>
            <div class="d-flex justify-content-between mt-3 border-bottom">
              <p>Size </p>
              <p><select name="size" required>
                    <option value="">Select size</option>
                    <option value="S">S</option>
                    <option value="M">M</option>
                    <option value="L">L</option>
                    <option value="XL">XL</option>
                    <option value="2XL">2XL</option>
                    <option value="3XL">3XL</option>
                    <option value="Voucher">Voucher</option>
              </select></p>
            </div>
            <% end %>

            <div class="d-flex justify-content-between mt-3 border-bottom">
              <p>Quantity </p>
              <p><span id="quantity-field">
                  <button type="button" id="down" onclick="setQuantity('down');setPrice();">-</button>
                  <input value="1", id="quantity" name="quantity" size="10" onkeyup="setPrice();">
                  <button type="button" id="up" onclick="setQuantity('up');setPrice();">+</button>
                </span></p>
            </div>

            <%= submit_tag 'Purchase', class: 'btn btn-flat w-100' %>
          <% end %>

          </div>
        </div>
      </div>
    </div>
</div>

<script>
    function setQuantity(upordown) {
    var quantity = document.getElementById('quantity');

    if (quantity.value > 1) {
        if (upordown == 'up'){++document.getElementById('quantity').value;}
        else if (upordown == 'down'){--document.getElementById('quantity').value;}}
    else if (quantity.value == 1) {
        if (upordown == 'up'){++document.getElementById('quantity').value;}}
    else
        {document.getElementById('quantity').value=1;}
}
</script>

<script>
  const startPrice = parseInt(document.getElementById('product-price').innerHTML)
  const setPrice = () => {
    let amount = document.getElementById('quantity').value;
    if (amount == "") {
      document.getElementById('product-price').innerHTML = 0
    } else {
    amount = parseInt(document.getElementById('quantity').value)
    let newPrice = startPrice * amount;
    document.getElementById('product-price').innerHTML = newPrice;
    console.log(amount)
      }
  }
</script>

app/views/products/top.html.erb
<h1>Top prices</h1>

<% @product.each do |product| %>
  <p><%= product.title %></p>
  <p><%= product.price %></p>
<% end %>

app/views/products/voucher.html.erb
<div class="container-black">
  <div class="navbar navbar-expand-sm navbar-light navbar-jb">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-black.jpg" %>
      <% end %>
  </div>

<div class="product-container">

<div class="index-container">
  <h1>VOUCHERS</h1>
    <div class="product-cards">
      <% @products.each do |product| %>
        <%= link_to product_path(product) do %>
          <div class="card-trip">
            <%= cl_image_tag product.pictures[0].photo %>
              <div class="card-trip-infos">
                <div>
                  <h2> <%= product.name %></h2>
                  <p> <%= product.color %></p>
                  <h3> <%= product.size %></h3>
                </div>
                <h1 class="card-trip-pricing"><h1><%= humanized_money_with_symbol(product.price) %></h1>
                <%#= cl_image_tag product.user.photo.key, class: "card-trip-user avatar-bordered" %>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

</div>